name: Benchmark

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run benchmarks
        run: cargo bench --verbose --features=bench
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          path: target/criterion/
          name: benchmark-results
