name: Benchmark

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install X11 libraries
        run: sudo apt-get update && sudo apt-get install pkg-config libxtst-dev libx11-dev libxi-dev -y
      - name: Run benchmarks
        run: cargo bench --verbose
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          path: target/criterion/
          name: benchmark-results
