name: Build RsHotkey

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install X11 libraries
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install pkg-config libxtst-dev libx11-dev libxi-dev -y
      - run: cargo build --all-targets --all-features
