name: CSpell

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-cspell:
    name: Lint CSpell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: streetsidesoftware/cspell-action@v1
        with:
          config: "cspell.json"
